// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Leave for reference", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetCachedSpectrum(System.Int32,System.Boolean)~pwiz.CLI.msdata.Spectrum")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Leave for reference", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetChargeStateValue(pwiz.CLI.msdata.Precursor)~System.Nullable{System.Int32}")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Leave for reference", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.ToFloatArray(pwiz.CLI.msdata.BinaryDataArray)~System.Single[]")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.DependencyLoader.FindPwizPath~System.String")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.Centroider.GetCentroidedData(System.Double[]@,System.Double[]@)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.Common.Collections.CollectionUtil.GetHashCodeDeep``1(System.Collections.Generic.IList{``0})~System.Int32")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetPwizSpectrum(System.Int32,System.Boolean)~pwiz.CLI.msdata.Spectrum")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetSpectrum(System.Int32,System.Boolean)~pwiz.ProteowizardWrapper.MsDataSpectrum")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~P:pwiz.ProteowizardWrapper.MsPrecursor.IsolationMz")]
[assembly: SuppressMessage("Simplification", "RCS1085:Use auto-implemented property.", Justification = "Leave as-is since the property name is not mz", Scope = "member", Target = "~P:pwiz.ProteowizardWrapper.Common.Chemistry.SignedMz.RawValue")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetChromatogram(System.Int32,System.String@,System.Single[]@,System.Single[]@,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetChromatogramId(System.Int32,System.Int32@)~System.String")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetDriftTimeMsec(System.Int32)~System.Nullable{System.Double}")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetInstantTimeAndPrecursors(System.Int32)~pwiz.ProteowizardWrapper.MsTimeAndPrecursors")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetMaxIonMobilityInList~System.Nullable{System.Double}")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetQcTraces~System.Collections.Generic.List{pwiz.ProteowizardWrapper.MsDataFileImpl.QcTrace}")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetScanTimes~System.Double[]")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetScanTimesAndMsLevels(System.Threading.CancellationToken,System.Double[]@,System.Byte[]@,System.Action{System.Int32,System.Int32},System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetSpectrum(System.Int32,System.Boolean)~pwiz.ProteowizardWrapper.MsDataSpectrum")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetTotalIonCurrent~System.Double[]")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.HasDriftTimeSpectraInList(pwiz.CLI.msdata.SpectrumList)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.HasIonMobilitySpectraInList~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.HasSrmSpectraInList(pwiz.CLI.msdata.SpectrumList)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Leave as-is to match the original version of this class", Scope = "member", Target = "~P:pwiz.ProteowizardWrapper.MsDataFileImpl.SpectrumList")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "type", Target = "~T:pwiz.ProteowizardWrapper.Common.Chemistry.eIonMobilityUnits")]
[assembly: SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetIonMobility(System.Int32)~pwiz.ProteowizardWrapper.Common.Chemistry.IonMobilityValue")]
[assembly: SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetScanTimes~System.Double[]")]
[assembly: SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:pwiz.ProteowizardWrapper.MsDataFileImpl.GetScanToIndexMapping~System.Collections.Generic.Dictionary{System.Int32,System.Int32}")]
[assembly: SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "Leave as-is for readability", Scope = "member", Target = "~P:pwiz.ProteowizardWrapper.MsDataFileImpl.HasCombinedIonMobilitySpectra")]
[assembly: SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "Leave as-is for readability", Scope = "member", Target = "~P:pwiz.ProteowizardWrapper.MsDataFileImpl.IsWatersLockmassCorrectionCandidate")]
[assembly: SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "Leave as-is for readability", Scope = "member", Target = "~P:pwiz.ProteowizardWrapper.MsDataFileImpl.SpectrumList")]
